//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishProduct
    {
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public Nullable<bool> IsBought { get; set; }
        public Nullable<System.DateTime> DateBought { get; set; }
    }
}
